//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQ_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Table
    {
        public int Admin_Id { get; set; }
        public string Name { get; set; }
        public string Email_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Mobile_Number { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> login_Date { get; set; }
        public Nullable<System.DateTime> last_Login_date { get; set; }
    }
}
