//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQ_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_Table
    {
        public int Answer_Table_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Tset_Id { get; set; }
        public Nullable<int> Question_Id { get; set; }
        public Nullable<int> Option_Id { get; set; }
        public Nullable<System.DateTime> TestAttended_Date { get; set; }
        public Nullable<bool> Attend_Test { get; set; }
    }
}
