//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQ_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Table
    {
        public Nullable<int> Subject_Id { get; set; }
        public int Question_Id { get; set; }
        public string Questions { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
