//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQ_PROJECT
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Subject_Table
    {
        public int Subject_Id { get; set; }
        public string Subjects { get; set; }
        public Nullable<int> Created_By { get; set; }
    }


    public class DataTableParameter
    {

        public List<DataTableColumn> Columns { get; set; }
        public int Draw { get; set; }
        public int Length { get; set; }
        public List<DataOrder> Order { get; set; }
        public Search Search { get; set; }
        public int Start { get; set; }
        public string TransactionId { get; set; }

    }

    public class Search
    {
        public bool Regex { get; set; }
        public string Value { get; set; }
    }

    public class DataTableColumn
    {
        public int Data { get; set; }
        public string Name { get; set; }
        public bool Orderable { get; set; }
        public bool Searchable { get; set; }
        public Search Search { get; set; }

    }

    public class DataOrder
    {
        public int Column { get; set; }
        public string Dir { get; set; }

    }


    public class DataTableResult
    {

        public List<Subject_Table> data = new List<Subject_Table>();

        public List<Subject_Table> ContainerData = new List<Subject_Table>();


        public int draw;

        public int recordsFiltered;

        public int recordsTotal;

        public string ToJSON()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
