//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQ_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Table
    {
        public int User_Id { get; set; }
        public string Name { get; set; }
        public string Email_Id { get; set; }
        public string Mobile_Number { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
    }
}
